### PR TITLE
Displace nginx init script to insert namespace wrapper

### PR DESCRIPTION
**Pull request by oa-metaswitch**
Proposed fix for https://github.com/Metaswitch/clearwater-issues/issues/2900

This one's potentially controlversial, so I'm very open to suggestions here. After nginx has been installed, this modification to the deb would:
- move /etc/init.d/nginx to /etc/init.d/nginx.clearwater-orig
- create a symlink /etc/init.d/nginx -> /etc/init.d/nginx.clearwater

We then install /etc/init.d/nginx.clearwater, which is a wrapper script that calls run-in-nginx-namespace. This has the effect of starting nginx in its own namespace if it has been configured.

In addition I've removed the calls to run-in-nginx-namesace from monit, since that now gets called by the init.d-script.

I've tested this on the old gaspode bifrost node, and as far as I can tell all the usual commands work as expected, with and without a namespace configured.

### CODE REVIEW

**Comment by oa-metaswitch** [comment]
Nigel: passing to you for first impressions.

**Comment by NigelThorpe** [comment]
I'm actually OK with this.  It works, and doesn't feel absurdly hacky to me.  Less so than munging nginx's init.d script in any case.

So it gets my stamp.  I'm interested to see what someone who knows Clearwater better has to say.

**Comment by oa-metaswitch** [comment]
Sweet. I'll pass it to the CW-team, then. :)

**Comment by johadalin** [comment]
@oa-metaswitch Have you done any thinking about this being run on other node types?

**Comment by johadalin** [comment]
I've had a look, and i can't see any way that this would inherently not work, but i'm aware i don't really have a ton of knowledge in the area, and something about it feels a bit odd. 
Only other way i could think of doing this though would be adding a monit script that checks for nginx processes running in the nginx-namespace, and if it finds none, kills any running nginx processes elsewhere, and then re-starts it in the right namespace, but that also feels a bit hacky.

I'm going to pass it across to @richardwhiuk for a second look.

**Comment by oa-metaswitch** [comment]
@johadalin Thanks for the review! I've thought a bit about whether this breaks something else:

The wrapper script will only try to run this in a separate namespace if the nginx-namespace variable is set in local_config, so e.g. homestead and homer should be unaffected by this change, provided nobody has configured an nginx-namespace for them. Now that you mention it, though: all hell could break loose if that was in shared_config rather than local_config. That's not where the docs tell you to configure it, but we also don't have any explicit checks to prevent it. Should something be added to cw-config to safeguard against that?

Aside from that, one other concern I can think of is that something else in e.g. homestead or homer also messes with the nginx init script. Browsing their repositories I couldn't see anything like that, so it should be fine.

**Comment by oa-metaswitch** [comment]
Thanks. I'll go ahead and merge this, then.

**Pull request merged**
